### ISSUE TITLE
Develop level generation algorithm

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/pyCaveExplorer#1]
We could start thinking about dungeon geeration, namely:
- Percentage chance for different grid spaces, item drops, etc
- Validation (can the player win the level? if not, generate a new one)
  - A solver was suggested for this
    - What if we started the player in the grid space that would take the most moves to win, but still be winnable?
- Which variables will be constant, and which variables might be changed later?
  - At later levels, will the player have the opportunity to impact the layout of the level?
- Will different game modes result in different chances of things appearing on a dungeon level?
- Will a set of levels be generated in advance, or are they generated on-the-fly, in between levels?
- Dragons

**Comment by ralphbean** [comment]
I think some of this is going on inside the Flash prototype already that @insanefastone is working on.

**Comment by ghost** [comment]
As of right now, there's a random number-controlled switch that has a weighted possibility of creating tiles that are either a path or a wall.
If it generates a path, it then runs a second switch that has a weighted chance of adding the start, goal, or a treasure inside that tile.
If a level is created without a start or a goal, it is scrapped and a new one is made.
The next thing we're doing is creating a search that will see if a path can be made from start to goal.

Also, I like the dragons idea.

**Comment by dtgay** [comment]
Level generation has basically been settled on, and the solver code is being implemented.
